version: "3.8"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - DB_NAME=brain_agriculture
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db
    profiles:
      - app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_agriculture
    ports:
      - "5432:5432"
    networks:
      - default

  test:
    build: .
    command: npm test
    environment:
      - NODE_ENV=test
      - DB_HOST=test_db
      - DB_NAME=test_brain_agriculture
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - test_db
    networks:
      - default
    profiles:
      - test

  test_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_brain_agriculture
    ports:
      - "5433:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
